### ISSUE TITLE
Fix links for change in space

### ISSUE THREAD

**Issue by jameslamb** [uptake/uptasticsearch#152]
This space was recently changed from `github.com/UptakeOpenSource` to `github.com/uptake`.

Need to change all the links in the repo! GitHub offers redirects automatically for a while, but we should update now. Also some integrations (like the Travis build status badge) do NOT offer redirects and are currently broken.

**Comment by dmaynard51** [comment]
May I try to take on this issue? Will be one of my first times trying to contribute.

**Comment by jameslamb** [comment]
@dmaynard51 hey, thank you for coming here to contribute! I have already opened #153 to address this particular issue, but we have other `good first issue` ones we'd love for you to pick up!

You can see all of them [here](https://github.com/uptake/uptasticsearch/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

For a first-time contributor, I think these would be good candidates:

* #142 
* #148 

Alternatively, we have the need for this exact same type of change in basically all of the `uptake` repos. Would you be willing to try for example https://github.com/uptake/pkgnet/issues/233?
