### ISSUE TITLE
add support for Elasticsearch 7

### ISSUE THREAD

**Issue by jameslamb** [uptake/uptasticsearch#155]
Review [the list of breaking changes in ES 7.x](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html). As of this writing, I don't know if `uptasticsearch` works with Elasticsearch 7.x.

To close this issue, add one or more ES 7.x tests to https://github.com/uptake/uptasticsearch/blob/master/.travis.yml and go from there.

**Comment by gabramson** [comment]
uptasticsearch appears to be broken for Elasticsearch 7.x. The error that I get is because ES 7 changed hits.total from a value to an object ([see here](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#hits-total-now-object-search-response). This causes `hits_to_pull <- min(firstResult[["hits"]][["total"]], max_hits)` to fail with
```
Error in min(firstResult[["hits"]][["total"]]) : 
  invalid 'type' (list) of argument
```

**Comment by jameslamb** [comment]
@gabramson thanks for the additional context!

I'd like to pick this up some time in the next few days and get this project back up and working with ES 7.

Thanks for using `uptasticsearch` and for taking the time to help us on this issue 😀

**Comment by gabramson** [comment]
My pleasure, James. Thanks for the tool! It's been extremely useful for me. Please let me know if I can be of any help moving this forward.

**Comment by jameslamb** [comment]
Ok @gabramson I _think_ I've fixed the R side. Assuming you have an ES7 cluster you're working with...would you be willing to test it out? We'll need to get the Python side working too (shouldn't take too long, possibly tomorrow) but I'd like to see if I have at least R working. We do have a bunch of tests that we run in CI but there's nothing like real-live use!

You could test by installing `uptasticsearch` from the branch I used in #161 with the following R code

```r
devtools::install_github("jameslamb/uptasticsearch@es7", subdir = "r-pkg")
```

Thanks!

**Comment by gabramson** [comment]
Great job, James! It works.

You were too fast, I didn't even think to check before I went ahead today and made the fix myself :)

Just to be sure, I re-installed your old version to verify the error and then installed the new version which resolved it, restarting R after each install.

Thanks,
Gary

**Comment by jameslamb** [comment]
Great! Ok then I'll keep working on #161 and try to get it merged + released to CRAN as soon as possible. You can keep building off of that branch to temporarily unblock you, and then follow the PR to see when it gets merged to `master`. I'll do a new release to CRAN as soon as we get that PR merged.
