### ISSUE TITLE
standardize directory names on kebob-case

### ISSUE THREAD

**Issue by jameslamb** [uptake/uptasticsearch#180]
Directories in this project are a mix of kebob case (`some-directory-name`) and snake case (`some_directory_name`). I know it's not super fun, but would love if someone standardized all of them on kebob case.

**Comment by chrsblck** [comment]
@jameslamb I could do this. It looks like it's only one directory right?

```
❯ find uptasticsearch -type d -name \*_\*
uptasticsearch/test_data
```

**Comment by jameslamb** [comment]
sure! I'll assign it to you
