### ISSUE TITLE
Add 'covr' to Suggests in the R package

### ISSUE THREAD

**Issue by jameslamb** [uptake/uptasticsearch#185]
This package uses `covr` to evalute the test coverage of the R package. It should be listed in `Suggests` in `R-package/DESCRIPTION`.

If you pick up this issue, please preserve the alphabetical ordering of dependencies in that file.

**Comment by jameslamb** [comment]
@yashgoswami-infy started to address this in #187 . I've asked that that change be put into a new PR. Leaving this comment so others know this issue is being worked on.

**Comment by yashgoswami-infy** [comment]
Hi, thanks for the clarifying. I have done the needful.
