### ISSUE TITLE
docs style: inline mentions of functions should use parentheses

### ISSUE THREAD

**Issue by jameslamb** [uptake/uptasticsearch#191]
References to functions with inline markup should use parentheses to clearly differentiate them from from references to packages, open source projects, and other things that are not functions.

In other words:

* good: "I used the function `es_search()` to do something heroic with `uptasticsearch`"
* bad: "I used the function `es_search` to do something heroic with `uptasticsearch`"

To close this issue, look through all the documentation in this project and add parentheses to any inline, marked-up references to functions. I know there is at least one use of `es_search` in . README.md...see if you can find others in other documentation!

**Comment by MattBSG** [comment]
Taking a look and doing this now

**Comment by jameslamb** [comment]
Thanks! Assigned the issue to you so no one scoops it
