### ISSUE TITLE
explicitly add language tags to all markdown code blocks

### ISSUE THREAD

**Issue by jameslamb** [uptake/uptasticsearch#196]
Currently, code blocks in `README.md` use generic markdown (\`\`\`), which means we're missing out on some syntax highlighting!

To close this issue, edit `README.md` so that each code block indicates the language (e.g. \`\`\`r). See [here](https://raw.githubusercontent.com/willdebras/ctar/master/README.md) as an example.

you can use:

* python: \`\`\`python
* R: \`\`\`r
* shell scripts: \`\`\`shell

**Comment by irfansener** [comment]
I am did it. Please check pr https://github.com/uptake/uptasticsearch/pull/199

**Comment by lakshay-angrish** [comment]
I would like to work on this. Could you please assign it to me?
